import type { Config } from "tailwindcss";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "snap-x",
    "snap-mandatory",
    "snap-center",
    "bg-BgCardModalComparePlans",
    "bg-BgCardModalComparePlansMobile",
    "BGStepB0",
    "BGCardStepB0",
  ],
  theme: {
    container: {
      center: true,
      padding: "5%",
      screens: {
        containerFull: "100%",
        containerLarge: "1440px",
      },
    },
    extend: {
      colors: {
        red25: "#FCEBEC",
        red50: "#F9D6D7",
        red100: "#F2B1B5",
        red200: "#E98A91",
        red300: "#DF646C",
        red400: "#D43E48",
        red500: "#8A1724",
        red600: "#73131D",
        red700: "#5D0F17",
        red800: "#460B11",
        red900: "#30070B",
        red950: "#1E0407",
        gray25: "#F6F6F6",
        gray50: "#F6F6F6",
        gray100: "#E7E7E7",
        gray200: "#D1D1D1",
        gray300: "#B0B0B0",
        gray400: "#888888",
        gray500: "#6D6D6D",
        gray600: "#5D5D5D",
        gray700: "#4F4F4F",
        gray800: "#454545",
        gray900: "#3D3D3D",
        gray950: "#191919",
        grayScale: "#494949",
        grayCoverage: "#FBFBFB",
        blueScale: "#02232D",
        bgSilderControl: "#A7A7A7",
        white: "#FFFFFF",
        light: "#FCEBEC",
        redSTD: "#8A1724",
        dark: "#5D0F17",
        auxiliary: "#F44336",
        green10: "#EEFFF3",
        green25: "#EAFBEC",
        green50: "#D3F6D9",
        green75: "#B1E4BF",
        green100: "#ADF0B8",
        green200: "#87E997",
        green300: "#61E277",
        green400: "#3DDB5B",
        green500: "#1EB03E",
        green600: "#189032",
        green700: "#137026",
        green800: "#0E501B",
        green900: "#093012",
        green950: "#051F0C",
        greenCoverage: "#00A650",
        blueBTN: "#239DE4",
        blueBORDER: "#185195",
      },
      backgroundImage: {
        "hero-about": "url('/bg-hero.webp')",
        "bg-banner-home": "url('/images/banner-home/bg-banner-home.webp')",
        BgHomeHelp: "url(/assets/img/bg-HomeHelp.webp)",
        BgHomeHelPlans: "url(/assets/img/bg-HomeHelpPlans.webp)",
        BgContact: "url(/assets/img/bg-contact.webp)",
        BgContactMobile: "url(/assets/img/bg-contactMobile.webp)",
        BgContactTablet: "url(/assets/img/bg-contactTablet.webp)",
        BgBannerHomeOurPlans: "url(/assets/img/bg-BannerHomeOurPlans.webp)",
        BgBannerHomeOurPlansMobile:
          "url(/assets/img/bg-BannerHomeOurPlansMobile.webp)",
        BgBannerHomeOurPlansTablet:
          "url(/assets/img/bg-BannerHomeOurPlansTablet.webp)",
        bgFooter: "url(/assets/icons/footer/bgFooter.png)",
        BgCardModalComparePlans: "url(/assets/img/BgCardModalComparePlan.webp)",
        BgCardModalComparePlansMobile:
          "url(/assets/img/BgCardModalComparePlansMobile.webp)",
        BGStepB0: "url(/assets/img/BGStepB0.webp)",
        BGCardStepB0: "url(/assets/img/BGCardStepB0.webp)",
        BGBlur: "url(/assets/img/BGBlur.webp)",
        BGoverlayMobile: "url(/assets/img/bgOverlayMobile.webp)",
      },
      fontFamily: {
        openSans: ["Open Sans", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        lato: ["Lato", "sans-serif"],
      },
      keyframes: {
        "modal-enter-mobile": {
          "0%": {
            transform: "translateY(100%)",
            opacity: "0",
          },
          "100%": {
            transform: "translateY(0)",
            opacity: "1",
          },
        },
        "modal-exit-mobile": {
          "0%": {
            transform: "translateY(0)",
            opacity: "1",
          },
          "100%": {
            transform: "translateY(100%)",
            opacity: "0",
          },
        },
        "modal-enter-desktop": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "modal-exit-desktop": {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        "bounce-x": {
          "0%, 100%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(5px)" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "bounce-x": "bounce-x 1s infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "modal-enter-mobile": "modal-enter-mobile 0.3s ease-out",
        "modal-exit-mobile": "modal-exit-mobile 0.3s ease-in",
      },
      ".WmaxContent": { width: "max-content" },
      ".HmaxContent": { height: "max-content" },
      transitionDuration: { 1500: "1500ms" },
    },
    screens: {
      "@mobile": "639px",
      "@tablet": "999px",
      "@laptop": "1025px",
      "@Desktop": "1281px",
      "@Desktop1440": "1440px",
      "@LargeDesktop": "1537px",
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    function ({ addUtilities, theme }: any) {
      const newUtilities = {
        ".TypographyPinter9": {
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "9px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
        },
        ".TypographyPinter10": {
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "10px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
        },
        ".TypographyPinter12R": {
          color: theme("colors.redSTD"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "120%",
          padding: "4px 8px",
          border: "1px solid #F9D6D7",
          borderRadius: "18px",
          background: theme("colors.red25"),
        },
        ".TypographyNavHeader": {
          color: "var(--color-gray950) ",
          fontFamily: "var(--font-inter) ",
          fontSize: "14px !important",
          fontStyle: "normal ",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          padding: "4px 8px",
          borderRadius: "8px",
          background: theme("colors.white"),
        },
        ".TypographyNavHeaderHover": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px !important",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          padding: "4px 8px",
          borderRadius: "8px",
          background: theme("colors.red25"),
        },
        ".TypographyMenuMobile": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-lato) ",
          fontSize: "20px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
          letterSpacing: "-0.3px",
        },
        ".TypographyH1home": {
          color: theme("colors.blueScale"),
          fontFamily: "var(--font-lato) ",
          fontSize: "40px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "120%",
        },
        ".TypographyH1homePlans": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-lato) ",
          fontSize: "48px",
          fontStyle: "normal",
          fontWeight: "900",
          lineHeight: "120%",
          letterSpacing: "-0.72px",
        },
        ".TypographyH1": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-lato) ",
          fontSize: "40px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "120%",
        },
        ".TypographyH1white": {
          color: theme("colors.white"),
          fontFamily: "var(--font-lato) ",
          fontSize: "40px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".TypographyH1mobile": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-lato) ",
          fontSize: "32px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "120%",
        },
        ".TypographyH2": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-lato) ",
          fontSize: "32px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "120%",
          letterSpacing: "-0.48px",
        },
        ".TypographyPinter14w400": {
          color: theme("colors.gray900"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
        },
        ".TypographyPinter14w400footer": {
          color: theme("colors.gray500"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          opacity: "0.7",
        },
        ".Typography14STDsidebar": {
          color: theme("colors.gray500"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
        },
        ".Typography14hoversidebarOK": {
          color: theme("colors.gray950"),
          fontFamily: theme("fontFamily.inter"),
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
        },
        ".TypographyPinter14w500": {
          color: theme("colors.gray900"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
        },
        ".TypographyPinter14w500g95": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
        },
        ".TypographyPinter16w400": {
          color: theme("colors.gray900"),
          fontFamily: theme("fontFamily.inter"),
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".TypographyPinterG400": {
          color: theme("colors.red500"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".TypographyPinter16white": {
          color: theme("colors.white"),
          fontFamily: theme("fontFamily.inter"),
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
        },
        ".TypographyPinter16w500g900": {
          color: theme("colors.gray900"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".TypographyPinter16w500g950": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".TypographyPinter16g950": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".TypographyPinter16w500g": {
          color: theme("colors.gray500"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".TypographyPinter16w600g": {
          color: theme("colors.gray500"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
        },
        ".TypographyPinter16w500r": {
          color: theme("colors.redSTD"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
        },
        ".TypographyPinter16redSTD": {
          color: theme("colors.redSTD"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
        },
        ".TypographyPinter16w500light": {
          color: theme("colors.light"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
        },
        ".TypographyPinter16w600": {
          color: theme("colors.redSTD"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
        },
        ".TypographyPinter18home": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-inter) ",
          fontSize: "18px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypographyPinter18w500": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-inter) ",
          fontSize: "18px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".btnYes": {
          color: theme("colors.greenCoverage"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "4px",
          borderRadius: "8px",
          background: theme("colors.green10"),
          border: "1px solid #B1E4BF",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".btnNot": {
          color: theme("colors.gray300"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "4px",
          borderRadius: "8px",
          background: theme("colors.gray50"),
          border: "1px solid #E7E7E7",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".btnCoverage": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
          display: "flex",
          justifyContent: "space-between",
          padding: "8px 16px",
          alignItems: "center",
          borderRadius: "8px",
          background: theme("colors.grayCoverage"),
          border: "1px solid #E7E7E7",
        },
        ".btnCoverageList": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        },
        ".TypographyPinter16green": {
          color: theme("colors.greenCoverage"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".TypographyPinter18w500g": {
          color: theme("colors.greenCoverage"),
          fontFamily: "var(--font-inter) ",
          fontSize: "18px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypographyPinter18w400": {
          color: theme("colors.gray900"),
          fontFamily: "var(--font-inter) ",
          fontSize: "18px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypographyPlato20": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-lato) ",
          fontSize: "20px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
          letterSpacing: "-0.32px",
        },
        ".TypographyPlato24": {
          color: theme("colors.gray950"),
          fontFamily: "var(--font-lato) ",
          fontSize: "24px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
          letterSpacing: "-0.36px",
        },
        ".TypographyPlato24light": {
          color: theme("colors.light"),
          fontFamily: "var(--font-lato) ",
          fontSize: "24px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
          letterSpacing: "-0.36px",
        },
        ".btnPrimary": {
          display: "inline-flex",
          padding: "7px 24px",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "4px",
          background: theme("colors.redSTD"),
          boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.08)",
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".btnForm": {
          display: "flex",
          padding: "12px 24px",
          justifyContent: "space-between",
          alignItems: "center",
          borderRadius: "4px",
          background: theme("colors.gray300"),
          boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.08)",
          color: theme("colors.gray500"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".btnFormHover": {
          display: "flex",
          padding: "12px 24px",
          justifyContent: "space-between",
          alignItems: "center",
          borderRadius: "4px",
          background: theme("colors.redSTD"),
          boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.08)",
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".btnScrollDown": {
          display: "flex",
          padding: "7px 16px",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "4px",
          background: theme("colors.redSTD"),
          boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.08)",
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".btnSecondary": {
          display: "inline-flex",
          padding: "12px 24px",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "4px",
          background: theme("colors.redSTD"),
          boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.08)",
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".btnTertiary": {
          display: "inline-flex",
          padding: "12px 24px",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "4px",
          background: theme("colors.blueBTN"),
          boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.08)",
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".btnLink": {
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".btnLinkForm": {
          display: "inline-flex",
          padding: "12px 24px",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "4px",
          border: "1px solid #8A1724",
          color: theme("colors.redSTD"),
        },
        ".textbtnLink": {
          color: theme("colors.redSTD"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".textBtn": {
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".layoutIntraMenu": {
          padding: "8px",
          justifyContent: "between",
          borderRadius: "30px",
          background: theme("colors.white"),
          boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.08)",
        },
        ".TypographyIntraMenu": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          diplay: "flex",
          padding: "8px 16px",
          justifyContent: "center",
        },
        ".TypographyIntraMenuSlider": {
          color: theme("colors.gray500"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
          padding: "4px 12px",
          border: "1px solid #E7E7E7",
          borderRadius: "100px",
          background: theme("colors.gray50"),
          boxShadow: " 0px 1px 2px 0px rgba(0, 0, 0, 0.10);",
        },
        ".TypographyIntraMenuSliderHover": {
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
          padding: "4px 12px",
          border: "1px solid #E7E7E7",
          borderRadius: "100px",
          background: theme("colors.redSTD"),
          boxShadow: " 0px 1px 2px 0px rgba(0, 0, 0, 0.10);",
        },
        ".TypographyTabIntraMenu": {
          background: theme("colors.redSTD"),
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          diplay: "flex",
          padding: "8px 16px",
          justifyContent: "center",
          borderRadius: "100px",
        },
        ".spaceFalseCoverage": {
          background: theme("colors.grayCoverage"),
          borderTop: "1px solid #E7E7E7",
          borderLeft: "1px solid #E7E7E7",
          borderRight: "1px solid #E7E7E7",
          borderBottom: "1px solid #E7E7E7",
          borderBottomLeftRadius: "10px",
          borderBottomRightRadius: "10px",
          justifyContent: "center",
        },
        ".styleSlider": {
          background: theme("colors.white"),
          border: "1px solid #E7E7E7",
          borderRadius: "17.5px",
          boxShadow:
            "0px 1px 2px 0px rgba(0, 0, 0, 0.16) inset, 0px 2px 4px 2px rgba(0, 0, 0, 0.06) inset",
        },
        ".styleSliderHover": {
          background: theme("colors.white"),
          border: "1px solid #8A1724",
          borderRadius: "17.5px",
          boxShadow:
            "0px 1px 2px 0px rgba(0, 0, 0, 0.16) inset, 0px 2px 4px 2px rgba(0, 0, 0, 0.06) inset",
        },
        ".stepSlider": {
          width: "8px",
          height: "8px",
          background: theme("colors.gray50"),
          border: "1px solid #E7E7E7",
          borderRadius: "8px",
          boxShadow:
            "-0.5px -1px 0.5px 0px rgba(0, 0, 0, 0.12) inset, -0.5px -1px 2px 0px rgba(0, 0, 0, 0.12) inset, 0.5px 1px 2px 0px rgba(255, 255, 255, 0.47) inset;",
          filter:
            "drop-shadow(0.5px 1px 1px rgba(0, 0, 0, 0.08)) drop-shadow(0px 0.3px 0.5px rgba(0, 0, 0, 0.08));",
        },
        ".stepSliderClick": {
          width: "48px",
          height: "32px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          cursor: "pointer",
          position: "relative",
          zIndex: 2,
        },
        ".stepSliderHover": {
          width: "8px",
          height: "8px",
          background: theme("colors.redSTD"),
          border: "2px solid #fff",
          borderRadius: "8px",
        },
        ".selectSliderHover": {
          width: "24px",
          height: "24px",
          background: theme("colors.redSTD"),
          border: "2px solid #fff",
          borderRadius: "50%",
          position: "relative",
        },
        ".selectSliderHover::after": {
          content: '""',
          display: "block",
          position: "absolute",
          top: "50%",
          left: "50%",
          width: "8px",
          height: "8px",
          background: "#fff",
          borderRadius: "50%",
          transform: "translate(-50%, -50%)",
        },
        ".fontScaleSlider": {
          color: theme("colors.gray500"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".fontScaleSelected": {
          color: theme("colors.redSTD"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".fontScaleSelectedback": {
          color: theme("colors.redSTD"),
          fontFamily: theme("fontFamily.inter"),
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.32px",
        },
        ".bgOverlayMobile": {
          background: "rgba(58, 58, 58, 0.58)",
          "backdrop-filter": "blur(5px)",
          "-webkit-backdrop-filter": "blur(5px)",
        },
        ".scrollbar-hidden": {
          "-ms-overflow-style": "none",
          "scrollbar-width": "none",
        },
        ".scrollbar-hide::-webkit-scrollbar": { display: "none" },
      };
      addUtilities(newUtilities);
    },
  ],
} satisfies Config;
