export const planosAceitos = [
  {
    id: 5,
    nome: "Bronze - 10.30.05 - CE",
    nome_comercial: "Bronze",
    registro_ans: 434295000,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 10,
    nome: "Dental Uni Misto",
    nome_comercial: "Misto",
    registro_ans: 459722092,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 11,
    nome: "Master",
    nome_comercial: "Master",
    registro_ans: 466574121,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 12,
    nome: "Prata - 10.30.03 - CE",
    nome_comercial: "Prata",
    registro_ans: 434297006,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 13,
    nome: "Basico",
    nome_comercial: "Basico",
    registro_ans: 705547991,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 14,
    nome: "Dental Uni Superior",
    nome_comercial: "Superior",
    registro_ans: 705824991,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 15,
    nome: "Avancado",
    nome_comercial: "Avancado",
    registro_ans: 421312992,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 16,
    nome: "Ouro - 10.30.01 - CE",
    nome_comercial: "Ouro",
    registro_ans: 434299002,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 17,
    nome: "Associacao Comercial",
    nome_comercial: "Associacao Comercial",
    registro_ans: 459285089,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 18,
    nome: "Superior Mais",
    nome_comercial: "Superior Mais",
    registro_ans: 459286087,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 19,
    nome: "Senior",
    nome_comercial: "Senior",
    registro_ans: 466570128,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 20,
    nome: "Premium",
    nome_comercial: "Premium",
    registro_ans: 466571126,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 21,
    nome: "Dental Uni CE I",
    nome_comercial: "Dental Uni CE I",
    registro_ans: 471446146,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 22,
    nome: "Prime",
    nome_comercial: "Prime",
    registro_ans: 466572124,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 23,
    nome: "Dental Uni Superior 25",
    nome_comercial: "Dental Uni Superior 25",
    registro_ans: 422427992,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Estadual",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 24,
    nome: "Superior",
    nome_comercial: "Superior",
    registro_ans: 459721094,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 25,
    nome: "Avancado",
    nome_comercial: "Avancado",
    registro_ans: 464766111,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 26,
    nome: "Supremo",
    nome_comercial: "Supremo",
    registro_ans: 466573122,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 27,
    nome: "Platinum",
    nome_comercial: "Platinum",
    registro_ans: 466575129,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 28,
    nome: "Dental Uni - CA I",
    nome_comercial: "Dental Uni - CA I",
    registro_ans: 471444140,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 29,
    nome: "Basico",
    nome_comercial: "Basico",
    registro_ans: 408866992,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 30,
    nome: "Superior",
    nome_comercial: "Superior",
    registro_ans: 408875991,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 31,
    nome: "Dental Uni Avancado 25",
    nome_comercial: "Dental Uni Avancado 25",
    registro_ans: 422948997,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 32,
    nome: "Ouro - 01.07 - IF",
    nome_comercial: "Ouro - 01.07 - IF",
    registro_ans: 434293003,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 33,
    nome: "Ouro Plus - 01.06 - IF",
    nome_comercial: "Ouro Plus - 01.06 - IF",
    registro_ans: 434294001,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 34,
    nome: "Prata - 10.30.04 - CA",
    nome_comercial: "Prata - 10.30.04 - CA",
    registro_ans: 434296008,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 35,
    nome: "Ouro - 10.30.02 - CA",
    nome_comercial: "Ouro - 10.30.02 - CA",
    registro_ans: 434298004,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 36,
    nome: "Sorriso",
    nome_comercial: "Sorriso",
    registro_ans: 461904108,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 37,
    nome: "Dental Uni - CA",
    nome_comercial: "Dental Uni - CA",
    registro_ans: 471443141,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 38,
    nome: "Dental Uni - CE",
    nome_comercial: "Dental Uni - CE",
    registro_ans: 471445148,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 39,
    nome: "Dental Uni Avancado",
    nome_comercial: "Dental Uni Avancado",
    registro_ans: 703454997,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 40,
    nome: "Top",
    nome_comercial: "Top",
    registro_ans: 466703124,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 41,
    nome: "Dental Uni Pos",
    nome_comercial: "Dental Uni Pos",
    registro_ans: 466797122,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 42,
    nome: "Dental Uni Avancado 25",
    nome_comercial: "Dental Uni Avancado 25",
    registro_ans: 467725121,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 43,
    nome: "Basico",
    nome_comercial: "Basico",
    registro_ans: 467726129,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 44,
    nome: "Dental Uni Superior 25",
    nome_comercial: "Dental Uni Pos",
    registro_ans: 467887127,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 45,
    nome: "MISTO",
    nome_comercial: "MISTO",
    registro_ans: 474513152,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Estados",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 46,
    nome: "AVANÇADO",
    nome_comercial: "AVANÇADO",
    registro_ans: 475168150,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 47,
    nome: "SUPERIOR",
    nome_comercial: "SUPERIOR",
    registro_ans: 475169158,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 48,
    nome: "SUPERIOR",
    nome_comercial: "SUPERIOR",
    registro_ans: 475318166,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 49,
    nome: "AVANÇADO",
    nome_comercial: "AVANÇADO",
    registro_ans: 475319164,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 50,
    nome: "AVANCADO MAIS",
    nome_comercial: "AVANCADO MAIS",
    registro_ans: 475441167,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 51,
    nome: "AVANÇADO 2",
    nome_comercial: "AVANÇADO 2",
    registro_ans: 475838162,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 52,
    nome: "AVANÇADO 1",
    nome_comercial: "AVANÇADO 1",
    registro_ans: 475839161,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Estadual",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 53,
    nome: "PLANO MISTO",
    nome_comercial: "PLANO MISTO",
    registro_ans: 475840164,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Estadual",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 54,
    nome: "AVANCADO 5",
    nome_comercial: "AVANCADO 5",
    registro_ans: 475985161,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 55,
    nome: "AVANCADO 4",
    nome_comercial: "AVANCADO 4",
    registro_ans: 475986169,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 56,
    nome: "AVANCADO 3",
    nome_comercial: "AVANCADO 3",
    registro_ans: 475987167,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Estadual",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 57,
    nome: "AVANCADO 6",
    nome_comercial: "AVANCADO 6",
    registro_ans: 475988165,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 58,
    nome: "DENTAL II CA BR",
    nome_comercial: "DENTAL AMPLO DOC",
    registro_ans: 476670169,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 59,
    nome: "DENTAL II CA GM PR",
    nome_comercial: "DENTAL AMPLO DOC",
    registro_ans: 476671167,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 60,
    nome: "DENTAL II CE GM PR",
    nome_comercial: "DENTAL AMPLO DOC",
    registro_ans: 476672165,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 61,
    nome: "DENTAL II CE BR",
    nome_comercial: "AVANC+DOC+ORT+PR+IMP",
    registro_ans: 476673163,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 62,
    nome: "DENTAL II PF BR",
    nome_comercial: "DENTAL AMPLO",
    registro_ans: 476697161,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 63,
    nome: "DENTAL I PF BR",
    nome_comercial: "DENTAL PRIME",
    registro_ans: 476698169,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 64,
    nome: "DENTAL III CA BR",
    nome_comercial: "DENTAL ELITE",
    registro_ans: 477854175,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 65,
    nome: "DENTAL III CE BR",
    nome_comercial: "DENTAL ELITE",
    registro_ans: 477855173,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Nacional",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 67,
    nome: "DENTAL III CA GM PR",
    nome_comercial: "DENTAL ELITE",
    registro_ans: 477856171,
    contratacao: "Coletivo por Adesão",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 68,
    nome: "DENTAL III CE GM PR",
    nome_comercial: "DENTAL ELITE",
    registro_ans: 477857170,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 69,
    nome: "DENTAL IV CE GM PR",
    nome_comercial: "DENTAL ORTOMAIS",
    registro_ans: 479276179,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 70,
    nome: "DENTAL IV GM PR IF",
    nome_comercial: "DENTAL ORTOMAIS",
    registro_ans: 479426175,
    contratacao: "Individual ou Familiar",
    segmentacao: "Odontológico",
    abrangencia: "Grupo de Municípios",
    situacao: "Ativo com Comercialização Suspensa",
  },
  {
    id: 71,
    nome: "PLANO DENTAL V CE EST RJ",
    nome_comercial: "PLANO DENTAL V CE EST RJ",
    registro_ans: 479607171,
    contratacao: "Coletivo Empresarial",
    segmentacao: "Odontológico",
    abrangencia: "Estadual",
    situacao: "Ativo com Comercialização Suspensa",
  },
];
